---
- hosts: all
  become: yes
  tasks:
  - name: update Apt packages
    apt:
      update_cache: yes
#Nodejs specific settings
#https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04
- hosts: app
  become: yes
  vars: 
    folderpath: /home/ansible/nodesetup
  tasks:
  - name: Creating Nodesetup directory
    path: "{{ folderpath }}"
    state: directory
    mode: 0755
  - name: Download node js package 
    command: "curl -sL https://deb.nodesource.com/setup_8.x -o {{folderpath}}/nodesource_setup.sh"
  - name: Installing Downloadedf file
    command: "sudo bash {{folderpath}}/nodesource_setup.sh"
