---
- hosts: all
  become: yes
  vars:
    package_name: apache2
  tasks: 
  - name: install webserver
    package: 
      name: "{{package_name}}"
      state: present

#ansible-playbook -e "package_name=httpd" webserver1.yaml
